---
extends: default
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 130
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
