---
name: Test Workflow
on: [push, pull_request]

jobs:
  static-check:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: 'x64'
      - name: Install Dependencies
        run: pip3 install -r requirements-dev.txt
      - name: Run Checks
        run: |
          yamllint -c=.yamllint.yaml ./
          black --exclude dags/*_dag.py --line-length=120 --check templates/ dags/ 
          isort --line-length=120  -c templates/ dags/
          flake8 --max-line-length=120 templates dags/
